Watchtogether/Controllers/AuthController.cs
using System;
using System.Threading.Tasks;
using DevOne.Security.Cryptography.BCrypt;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Watchtogether.DTO;
using Watchtogether.Factory;
using Watchtogether.Logic.Interface;
using Watchtogether.Model.Models;
using Watchtogether.Utils;

namespace Watchtogether.Controllers
{
    [Route("auth")]
    public class AuthController : Controller
    {
        private readonly IUserLogic _userLogic;

        public AuthController(IConfiguration config, IHostingEnvironment env, Factory.Factory factory)
        {
            _userLogic = factory.GetUserLogic(Engine.MySql);
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(LoginDto login)
        {
            User user;
            try
            {
                user = _userLogic.Login(login.Email, login.Password);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                return RedirectToAction("Login", "Home");
            }

            if (user == null)
            {
                return RedirectToAction("Login", "Home");
            }

            await AuthUtils.SignInUser(HttpContext, user.Email);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> Register(RegisterDto dto)
        {
            try
            {
                _userLogic.Register(dto.Username, dto.Password, dto.Email, dto.Birthday);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                return RedirectToAction("Register", "Home");
            }

            await AuthUtils.SignInUser(HttpContext, dto.Email);
            return RedirectToAction("Index", "Account");
        }

        [HttpGet]
        [Route("logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Watchtogether/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Watchtogether.DTO;
using Watchtogether.Exceptions;
using Watchtogether.Factory;
using Watchtogether.Logic.Interface;
using Watchtogether.Model.Models;
using Watchtogether.Utils;
using Watchtogether.ViewModels;

namespace Watchtogether.Controllers
{
    [Route("groups")]
    public class GroupController : Controller
    {
        private readonly IGroupLogic _groupLogic;
        private readonly IUserLogic _userLogic;

        public GroupController(IConfiguration config, IHostingEnvironment env, Factory.Factory factory)
        {
            _groupLogic = factory.GetGroupLogic(Engine.MySql);
            _userLogic = factory.GetUserLogic(Engine.MySql);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Index()
        {
            var user = _userLogic.FindByEmail(AuthUtils.GetCurrentUserMail(HttpContext));
            ViewBag.Groups = _groupLogic.GetUserGroups(user);
            return View();
        }

        [Authorize]
        [HttpGet("{id}")]
        public IActionResult OpenGroup(int id)
        {
            var model = new GroupViewModel {Group = _groupLogic.Read(id), Users = _groupLogic.GetUsersFromGroup(id)};
            return View(model);
        }

        [Authorize]
        [HttpGet("edit/{id}")]
        public IActionResult Edit(int id)
        {
            ViewBag.Group = _groupLogic.Read(id);
            return View();
        }

        [Authorize]
        [HttpPost("create")]
        public IActionResult CreateGroup(GroupCreationDTO dto)
        {
            var user = _userLogic.FindByEmail(AuthUtils.GetCurrentUserMail((HttpContext)));
            var group = _groupLogic.Create(new Group
            {
                Name = dto.Name,
                Description = dto.Description,
                OwnerId = user.Id,
                CreatorId = user.Id,
                CreationDate = DateTime.Now
            });

            _groupLogic.AddUser(group, user);
            return RedirectToAction("OpenGroup", new {id = group.Id});
        }

        [Authorize]
        [HttpGet("create")]
        public IActionResult Create()
        {
            return View();
        }
        
        [Authorize]
        [HttpPost("{groupId}/add/{username}")]
        public IActionResult AddUser(int groupId, string username)
        {
            var group = _groupLogic.Read(groupId);
            try
            {
                var user = _userLogic.FindByUsername(username);
                _groupLogic.AddUser(group, user);
            }
            catch (WatchtogetherException e)
            {
                return Content(e.Message);
            }

            return Ok("User was added");
        }

        [Authorize]
        [HttpPost("{groupId}/remove/{username}")]
        public IActionResult RemoveUser(int groupId, string username)
        {
            var group = _groupLogic.Read(groupId);

            try
            {
                var user = _userLogic.FindByUsername(username);
                _groupLogic.RemoveUser(group, user);
            }
            catch (WatchtogetherException e)
            {
                return Content(e.Message);
            }

            return Ok("User was removed");
        }
    }
}

Watchtogether/Controllers/RoomController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Watchtogether.DTO;
using Watchtogether.Exceptions;
using Watchtogether.Factory;
using Watchtogether.Logic.Interface;
using Watchtogether.Model.Models;
using Watchtogether.Utils;
using Watchtogether.ViewModels;

namespace Watchtogether.Controllers
{
    [Route("rooms")]
    public class RoomController : Controller
    {
        private readonly IRoomLogic _roomLogic;
        private readonly IUserLogic _userLogic;
        private readonly IGroupLogic _groupLogic;

        public RoomController(IConfiguration config, IHostingEnvironment env, Factory.Factory factory)
        {
            _roomLogic = factory.GetRoomLogic(Engine.MySql);
            _userLogic = factory.GetUserLogic(Engine.MySql);
            _groupLogic = factory.GetGroupLogic(Engine.MySql);
        }

        [Authorize]
        public IActionResult Index()
        {
            var user = _userLogic.FindByEmail(AuthUtils.GetCurrentUserMail(HttpContext));
            var rooms = _roomLogic.GetAllAccessibleRooms(user);

            return View(new RoomsViewModel
            {
                Rooms = rooms
            });
        }


        [Authorize]
        [Route("{id}")]
        public IActionResult OpenRoom(int id)
        {
            var room = _roomLogic.Read(id);
            if (room == null)
            {
                return NotFound("Room not found");
            }

            var user = _userLogic.FindByEmail(AuthUtils.GetCurrentUserMail(HttpContext));
            var userGroups = _groupLogic.GetUserGroups(user);
            var currentGroups = _roomLogic.GetGroups(room);


            var viewmodel = new RoomViewModel
            {
                Room = room,
                UserGroups = userGroups.Where(group => currentGroups.All(currentGroup => currentGroup.Id != @group.Id)),
                CurrentGroups = currentGroups,
            };
            return View(viewmodel);
        }


        [HttpGet]
        [Route("create")]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        [Authorize]
        public ActionResult CreateRoom(RoomCreationDto dto)
        {
            var user = _userLogic.FindByEmail(AuthUtils.GetCurrentUserMail(HttpContext));

            var room = new Room
            {
                Name = dto.Name,
                Public = dto.Public,
                Description = dto.Description,
                CreationDate = DateTime.Now,
                OwnerId = user.Id,
                CreatorId = user.Id
            };

            room = _roomLogic.Create(room);
            return RedirectToAction("OpenRoom", new {id = room.Id});
        }

        [HttpGet]
        [Route("{id}/edit")]
        [Authorize]
        public IActionResult Edit(int id)
        {
            var room = _roomLogic.Read(id);
            return View(room);
        }

        [HttpPost]
        [Route("{id}/edit")]
        [Authorize]
        public IActionResult EditRoom(RoomCreationDto dto, int id)
        {
            var room = new Room
            {
                Id = id,
                Name = dto.Name,
                Public = dto.Public,
                Description = dto.Description
            };

            room = _roomLogic.Update(room);
            return RedirectToAction("OpenRoom", new {id});
        }

        [HttpPost]
        [Route("{roomId}/group/add/{groupId}")]
        [Authorize]
        public IActionResult AddGroup(int roomId, int groupId)
        {
            var room = _roomLogic.Read(roomId);
            var group = _groupLogic.Read(groupId);

            try
            {
                _roomLogic.AddGroup(room, group);
            }
            catch (WatchtogetherException e)
            {
                return Ok(e.Message);
            }

            return Ok("The group was added to the room");
        }

        [HttpPost]
        [Route("{roomId}/group/remove/{groupId}")]
        [Authorize]
        public IActionResult RemoveGroup(int roomId, int groupId)
        {
            var room = _roomLogic.Read(roomId);
            var group = _groupLogic.Read(groupId);

            try
            {
                _roomLogic.RemoveGroup(room, group);
            }
            catch (WatchtogetherException e)
            {
                return Ok(e.Message);
            }

            return Ok("The group was removed from the room");
        }
    }
}

Watchtogether/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title> @ViewData["Title"] - Watch Together now!</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/site.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/rooms.css"/>
</head>
<body>
<partial name="_NavigationPartial"/>
<div class="container">
    @RenderBody()
</div>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>


@RenderSection("Scripts", required: false)

Watchtogether/Views/Shared/_NavigationPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <div class="container">
        <a class="navbar-brand" href="#">Watchtogether</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
       
        
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Group" asp-action="Index">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Room" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Index">My profile (@User.Claims.ToList().First(claim => claim.Subject.NameClaimType == "email").Value)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Register">Register</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</nav>